### ISSUE TITLE
ارسال همه دانلود‌ها به پرسپولیس

### ISSUE THREAD

**Issue by z-avanes** [persepolisdm/persepolis-chrome-wrapper#2]
سلام خسته نباشید
مرسی از افزونه خوبتون واقعا کروم در لینوکس کمبود این افزونه رو داشت
یه موضوعی که هست چه طور میشه همه دانلود‌ها در کروم به صورت خودکار به پرسپولیس ارسال بشه و دیگه نیازی به راست کلیک و انتخاب  دانلود با پرسپولیس در منو نباشه؟

**Comment by alireza-amirsamimi** [comment]
@z-avanes سلام
ممنونم از لطف و محبت شما
این مشکل رو حل کردیم.
انشاالله با انتشار نسخه جدید پرسپولیس ۲.۴ دیگه دانلود ها به شکل خودکار ارسال از کروم به پرسپولیس ارسال خواهند شد :)
