### ISSUE TITLE
باز کردن پرسپولیس برای همه ی فایل ها

### ISSUE THREAD

**Issue by engmmrj** [persepolisdm/persepolis-chrome-wrapper#5]
سلام
این افزونه کروم برای همه ی فایل ها میاد پرسپولیس رو باز میکنه . مثلا برای فایل های متنی مثل پی دی اف نباید باز کنه باید یک لیست ایگنور بشه براش درست کرد تا برای فایل های دلخواه فقط باز بشه

**Comment by JafarAkhondali** [comment]
سلام
میشه نمونه لینک بدین؟ ورژن کروم و ورژن افزونه رو هم ذکر کنید.
برای مشکلی که گفتین این کار توی اهدافمون بوده، روش کار میکنیم :+1:

**Comment by JafarAkhondali** [comment]
فعلا توی افزونه هم میتونین لیست ایگنور داشته باشین ولی بر اساس فرمت  اسم کار میکنه نه فرمت  واقعی 
![screenshot_20170523_181221](https://cloud.githubusercontent.com/assets/11364402/26357133/9395151a-3fe3-11e7-8ec3-7c5705318084.png)

**Comment by engmmrj** [comment]
کروم 58 و ورژن افزونه 1.2 هست
مثلا از داخل صفحه کروم اکستنش ادد میکنی پرسپولیس باز میشه برای دانلودش!

**Comment by JafarAkhondali** [comment]
از ایگنور لیستی که توی عکس نشون دادیم استفاده کنین اگه مشکلی بود اطلاع بدین
